export const FETCH_TWENTY_POKEMONS = "FETCH_TWENTY_POKEMONS";
export const FETCH_TWENTY_POKEMONS_SUCCESS = "FETCH_TWENTY_POKEMONS_SUCCESS";
export const FETCH_TWENTY_POKEMONS_ERROR = "FETCH_TWENTY_POKEMONS_ERROR";
export const FETCH_POKEMON = "FETCH_POKEMON";
export const FETCH_POKEMON_SUCCESS = "FETCH_POKEMON_SUCCESS";
export const FETCH_POKEMON_ERROR = "FETCH_POKEMON_ERROR";
